import { type NextPage } from "next";
import Head from "next/head";
//import Link from "next/link";
import { SignIn, useUser } from "@clerk/nextjs";

import { Jost } from "next/font/google";

const jost = Jost({ subsets: ["latin"] });
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <style jsx global>
          {`
            :root {
              --lora-font: ${jost.style.fontFamily};
            }
          `}
        </style>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && <SignIn />}
      </main>
    </>
  );
};

export default Home;
